# -*- coding: utf-8 -*-
"""P-value-calculation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WJt0wJD8lw1CaRhi_IQrC0YtOgxQPRk5
"""

import numpy as np
from scipy import stats

# Example data
group1 = np.array([(-5.25, -4.62), (-5.25, -5.38), (-5, -6.41), (-4.63, -5.28), (-5.13, -5.38), (-5.38, -5.38), (-3.0, -5.03), (-6.0, -4.92), (-4.13, -6.51), (-6.0,-4.97),(-3.88, -4.1)])
group2 = np.array([(-2.5, -2.15), (2.13, -3.44), (-3.75, -2.77), (-1.13, -2.92), (-1.75, -5.08),(-3.75,-4.56),(-2.5,-1.9),(-2.88,-2.36),(1.25,-2.41),(-3.5,-3.95),(-1.88,-2.36)])

# Split the pairs into first and second elements
group1_first = np.array([item[0] for item in group1])  # First elements of the pairs
group2_first = np.array([item[0] for item in group2])  # First elements of the pairs

group1_second = np.array([item[1] for item in group1])  # Second elements of the pairs
group2_second = np.array([item[1] for item in group2])  # Second elements of the pairs

# Perform paired t-test on the x values
t_stat_first, p_value_first = stats.ttest_ind(group1_first, group2_first)

# Perform paired t-test on the y values
t_stat_second, p_value_second = stats.ttest_ind(group1_second, group2_second)

# Print the results
print(f"T-statistic-x: {t_stat_first}")
print(f"P-value-x: {p_value_first}")

print(f"T-statistic-y: {t_stat_second}")
print(f"P-value-y: {p_value_second}")

alpha = 0.05  # Significance level

# Interpret the X element p-value
if p_value_first < alpha:
    print("Reject the null hypothesis for first elements: There is a significant difference between the first elements.")
else:
    print("Fail to reject the null hypothesis for first elements: No significant difference between the first elements.")

# Interpret the Y element p-value
if p_value_second < alpha:
    print("Reject the null hypothesis for second elements: There is a significant difference between the second elements.")
else:
    print("Fail to reject the null hypothesis for second elements: No significant difference between the second elements.")

