# -*- coding: utf-8 -*-
"""P-value-calculation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WJt0wJD8lw1CaRhi_IQrC0YtOgxQPRk5
"""

import numpy as np
from scipy import stats

# Example data where each point is a pair
group1 = np.array([(-5.25, -4.62), (-5.25, -5.38), (-5, -6.41), (-4.63, -5.28), (-5.13, -5.38), (-5.38, -5.38), (-3.0, -5.03), (-6.0, -4.92), (-4.13, -6.51), (-6.0,-4.97),(-3.88, -4.1)])
group2 = np.array([(-2.5, -2.15), (2.13, -3.44), (-3.75, -2.77), (-1.13, -2.92), (-1.75, -5.08),(-3.75,-4.56),(-2.5,-1.9),(-2.88,-2.36),(1.25,-2.41),(-3.5,-3.95),(-1.88,-2.36)])

# Calculate the Euclidean distance between the corresponding elements of each pair
distances = np.sqrt(np.sum((group1 - group2)**2, axis=1))  # Euclidean distance between pairs

# Perform a paired t-test on the distances
t_stat, p_value = stats.ttest_1samp(distances, 0)

# Print the results
print(f"T-statistic: {t_stat}")
print(f"P-value: {p_value}")

# Interpret the p-value
alpha = 0.05  # Significance level
if p_value < alpha:
    print("Reject the null hypothesis: There is a significant difference between the pairs.")
else:
    print("Fail to reject the null hypothesis: No significant difference between the pairs.")

